// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using weatherescu_test_2.Models;

#nullable disable

namespace weatherescu_test_2.Migrations
{
    [DbContext(typeof(WeatherContext))]
    [Migration("20250513162300_AddIdentityTables")]
    partial class AddIdentityTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("weatherescu_test_2.Models.City", b =>
                {
                    b.Property<int>("CityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityID"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            CityID = 1,
                            Country = "Romania",
                            Name = "Craiova"
                        },
                        new
                        {
                            CityID = 2,
                            Country = "Romania",
                            Name = "Bucuresti"
                        },
                        new
                        {
                            CityID = 3,
                            Country = "Romania",
                            Name = "Braila"
                        },
                        new
                        {
                            CityID = 4,
                            Country = "Romania",
                            Name = "Cluj-Napoca"
                        },
                        new
                        {
                            CityID = 5,
                            Country = "Romania",
                            Name = "Iasi"
                        });
                });

            modelBuilder.Entity("weatherescu_test_2.Models.Humidity", b =>
                {
                    b.Property<int>("HumidityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HumidityID"));

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("HumidityID");

                    b.HasIndex("CityID")
                        .IsUnique();

                    b.ToTable("Humidities");

                    b.HasData(
                        new
                        {
                            HumidityID = 1,
                            CityID = 1,
                            Value = 70
                        },
                        new
                        {
                            HumidityID = 2,
                            CityID = 2,
                            Value = 80
                        },
                        new
                        {
                            HumidityID = 3,
                            CityID = 3,
                            Value = 75
                        },
                        new
                        {
                            HumidityID = 4,
                            CityID = 4,
                            Value = 65
                        },
                        new
                        {
                            HumidityID = 5,
                            CityID = 5,
                            Value = 85
                        });
                });

            modelBuilder.Entity("weatherescu_test_2.Models.Precipitation", b =>
                {
                    b.Property<int>("PrecipitationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrecipitationID"));

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("PrecipitationID");

                    b.HasIndex("CityID")
                        .IsUnique();

                    b.ToTable("Precipitations");

                    b.HasData(
                        new
                        {
                            PrecipitationID = 1,
                            CityID = 1,
                            Value = 10
                        },
                        new
                        {
                            PrecipitationID = 2,
                            CityID = 2,
                            Value = 20
                        },
                        new
                        {
                            PrecipitationID = 3,
                            CityID = 3,
                            Value = 30
                        },
                        new
                        {
                            PrecipitationID = 4,
                            CityID = 4,
                            Value = 40
                        },
                        new
                        {
                            PrecipitationID = 5,
                            CityID = 5,
                            Value = 50
                        });
                });

            modelBuilder.Entity("weatherescu_test_2.Models.Pressure", b =>
                {
                    b.Property<int>("PressureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PressureID"));

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("PressureID");

                    b.HasIndex("CityID")
                        .IsUnique();

                    b.ToTable("Pressures");

                    b.HasData(
                        new
                        {
                            PressureID = 1,
                            CityID = 1,
                            Value = 1000
                        },
                        new
                        {
                            PressureID = 2,
                            CityID = 2,
                            Value = 1010
                        },
                        new
                        {
                            PressureID = 3,
                            CityID = 3,
                            Value = 1020
                        },
                        new
                        {
                            PressureID = 4,
                            CityID = 4,
                            Value = 1030
                        },
                        new
                        {
                            PressureID = 5,
                            CityID = 5,
                            Value = 1040
                        });
                });

            modelBuilder.Entity("weatherescu_test_2.Models.Temperature", b =>
                {
                    b.Property<int>("TemperatureID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemperatureID"));

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("TemperatureID");

                    b.HasIndex("CityID")
                        .IsUnique();

                    b.ToTable("Temperatures");

                    b.HasData(
                        new
                        {
                            TemperatureID = 1,
                            CityID = 1,
                            Value = 6
                        },
                        new
                        {
                            TemperatureID = 2,
                            CityID = 2,
                            Value = 10
                        },
                        new
                        {
                            TemperatureID = 3,
                            CityID = 3,
                            Value = 8
                        },
                        new
                        {
                            TemperatureID = 4,
                            CityID = 4,
                            Value = 5
                        },
                        new
                        {
                            TemperatureID = 5,
                            CityID = 5,
                            Value = 7
                        });
                });

            modelBuilder.Entity("weatherescu_test_2.Models.WeatherCondition", b =>
                {
                    b.Property<int>("WeatherConditionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherConditionID"));

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WeatherConditionID");

                    b.HasIndex("CityID")
                        .IsUnique();

                    b.ToTable("WeatherConditions");

                    b.HasData(
                        new
                        {
                            WeatherConditionID = 1,
                            CityID = 1,
                            Description = "Sunny"
                        },
                        new
                        {
                            WeatherConditionID = 2,
                            CityID = 2,
                            Description = "Rainy"
                        },
                        new
                        {
                            WeatherConditionID = 3,
                            CityID = 3,
                            Description = "Cloudy"
                        },
                        new
                        {
                            WeatherConditionID = 4,
                            CityID = 4,
                            Description = "Snowy"
                        },
                        new
                        {
                            WeatherConditionID = 5,
                            CityID = 5,
                            Description = "Windy"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("weatherescu_test_2.Models.Humidity", b =>
                {
                    b.HasOne("weatherescu_test_2.Models.City", "City")
                        .WithOne("Humidity")
                        .HasForeignKey("weatherescu_test_2.Models.Humidity", "CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("weatherescu_test_2.Models.Precipitation", b =>
                {
                    b.HasOne("weatherescu_test_2.Models.City", "City")
                        .WithOne("Precipitation")
                        .HasForeignKey("weatherescu_test_2.Models.Precipitation", "CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("weatherescu_test_2.Models.Pressure", b =>
                {
                    b.HasOne("weatherescu_test_2.Models.City", "City")
                        .WithOne("Pressure")
                        .HasForeignKey("weatherescu_test_2.Models.Pressure", "CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("weatherescu_test_2.Models.Temperature", b =>
                {
                    b.HasOne("weatherescu_test_2.Models.City", "City")
                        .WithOne("Temperature")
                        .HasForeignKey("weatherescu_test_2.Models.Temperature", "CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("weatherescu_test_2.Models.WeatherCondition", b =>
                {
                    b.HasOne("weatherescu_test_2.Models.City", "City")
                        .WithOne("WeatherCondition")
                        .HasForeignKey("weatherescu_test_2.Models.WeatherCondition", "CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("weatherescu_test_2.Models.City", b =>
                {
                    b.Navigation("Humidity");

                    b.Navigation("Precipitation");

                    b.Navigation("Pressure");

                    b.Navigation("Temperature");

                    b.Navigation("WeatherCondition");
                });
#pragma warning restore 612, 618
        }
    }
}
